
#Keycloak
keycloak:
  auth-server-url: http://thor:8180/auth
  realm: avizandum
  resource: avizandum-identity
  public-client: true
  principal-attribute: preferred_username

#Metrics
management:
  metrics:
    export:
      influx:
        enabled: true
        db: avizandum
        user-name: avi
        password: hellogithub
        step: 15s
        uri: http://thor:8086
        autoCreateDb: false


# MySQL
spring:
  datasource:
    url: jdbc:mysql://thor:3306/avizandum?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: avizandumapp
    password: hellogithub
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
    show-sql: true