# MySQL
spring:
  datasource:
    url: ${springDatasourceUrl}
    username: ${springDatasourceUsername}
    password: ${springDatasourcePassword}
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
    show-sql: true

#Keycloak
keycloak:
  auth-server-url: ${keycloakAuthServerUrl}
  realm: ${keycloakRealm}
  resource: ${keycloakResource}
  public-client: true
  principal-attribute: preferred_username

#Metrics
management:
  metrics:
    export:
      influx:
        enabled: true
        db: avizandum
        user-name: ${influxUserName}
        password: ${influxPassword}
        step: 15s
        uri: ${influxUri}
        autoCreateDb: false

server:
  port: 8090
